name = "turing-games"
pages_build_output_dir = "./dist"

compatibility_date = "2024-05-14"
# node_compat = true

[env.preview.vars]
HONO_ENV = "development"
VITE_ENV = "production"
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_YmVjb21pbmctc2hhcmstMTAuY2xlcmsuYWNjb3VudHMuZGV2JA"

[env.production.vars]
HONO_ENV = "production"
VITE_ENV = "production"
VITE_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsudHVyaW5ncG9rZXIuY29tJA"

# [[kv_namespaces]]
binding = "turingpoker_dev"
id = "d32c16c2fa6b4d2099cdcbd5d023662f"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "turingpoker_dev"
# database_id = "20e9a3cf-ec9e-4cfe-a7d4-7e39ae3f3a53"

# [ai]
# binding = "AI"