name = "turing-games"
pages_build_output_dir = "./dist"

compatibility_date = "2024-05-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
HONO_ENV = "development"
BOT_SECRET_KEY = "95eff06e276944f587efa311d5b402b3da520af77cfaf3ca78bd7e6eb3776b04"

[env.preview.vars]
HONO_ENV = "production"
BOT_SECRET_KEY = "95eff06e276944f587efa311d5b402b3da520af77cfaf3ca78bd7e6eb3776b04"

[env.production.vars]
HONO_ENV = "production"
BOT_SECRET_KEY = "95eff06e276944f587efa311d5b402b3da520af77cfaf3ca78bd7e6eb3776b04"

[[d1_databases]]
binding = "DB"
database_name = "turinggames_prod"
database_id = "054c910b-1580-4cfc-8ea4-1874bb729251"
preview_database_id = "bbb9dcef-4175-4cbe-b26e-e2bf75852ea5"

[env.preview]
d1_databases = [
    { binding = "DB", database_name = "turinggames_dev", database_id = "bbb9dcef-4175-4cbe-b26e-e2bf75852ea5" },
]

[env.production]
d1_databases = [
    { binding = "DB", database_name = "turinggames_prod", database_id = "054c910b-1580-4cfc-8ea4-1874bb729251" },
]